services:
  ecd15:
    container_name: ecd15
    image: ecd15:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
networks:
  default:
    driver: bridge
